### ISSUE TITLE
no choice for Caitiff

### ISSUE THREAD

**Issue by CalumWulfe** [Odin94/Progeny-vtm-v5-character-creator#1]
noticed there's not option to be a Caitiff/Clan-less

**Comment by burakygzgll** [comment]
thats litterly so true... I may be gonna look for it to code but I dont have enough time for this rn...

**Comment by Odin94** [comment]
Hi! The reason I didn't add Caitiff (yet) is that they don't have clan-specific disciplines and because of that the Discipline picking page would need to work differently for them.

If you (or anyone else) want to contribute a PR to add Caitiff, it'd be cool if you did something like:
* Add a `clanDisciplines` attribute to the `Character` type
* In DisciplinePicker, replace the call to `getDisciplinesForClan(character.clan)` with `character.clanDisciplines`
* Set `clanDisciplines` on `character` to `getDisciplinesForClan(character.clan)` when picking a Clan
* When picking Caitiff, open a modal for picking your disciplines (inspiration code for the modal can be found in `PredatorTypeModal.tsx`) and assign the picked disciplines instead of `getDisciplinesForClan(character.clan)`

Also let me know ahead of time if you want to work on this and give me a rough timeline on completion, just so nobody else (or I myself) works on it at the same time and we do duplicate work :)

**Comment by Odin94** [comment]
@CalumWulfe @Fiobrum 
I just added Caitiffs, check it out and let me know what you think :)
